### ISSUE TITLE
How to use this library to do secp256k1 signing?

### ISSUE THREAD

**Issue by t-anyu** [piggypiggy/secp256k1-x64#1]
Hey,

I've managed to get x, y = k*G, but how should I calculate r = x mod n and s = k^-1 * (z + r*dA) mod n?

Thanks!

**Comment by piggypiggy** [comment]
This library can only do point addition and multiplication on secp256k1, modular addition, multiplication for secp256k1 modulo p=0xFFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE FFFFFC2F, it cannot do arithmetic for other modulo nor sign message.

You may refer to my bignum library [fp256](https://github.com/piggypiggy/fp256), it can do many arithmetic on 256bit integer very efficiently, including all arithmetic used in sign/verify.

Be aware that these implementations are NOT secure.

**Comment by t-anyu** [comment]
Hey, ok thanks!

Unsafety noted.
